### ISSUE TITLE
Disposing transports can hang when running in .NET framework

### ISSUE THREAD

**Issue by eiriktsarpalis** [modelcontextprotocol/csharp-sdk#255]
This is because the read loop in the core transport abstraction uses `TextWriter`:

https://github.com/modelcontextprotocol/csharp-sdk/blob/08f9cdbf7d802e0db32df8d07de86aed217d1302/src/ModelContextProtocol/Protocol/Transport/StreamClientSessionTransport.cs#L99

https://github.com/modelcontextprotocol/csharp-sdk/blob/08f9cdbf7d802e0db32df8d07de86aed217d1302/src/ModelContextProtocol/Protocol/Transport/StreamServerTransport.cs#L103

Which in `netstandard2.0` is not cancellable and requires a polyfill that does not properly honor the cancellation token:

https://github.com/modelcontextprotocol/csharp-sdk/blob/08f9cdbf7d802e0db32df8d07de86aed217d1302/src/Common/Polyfills/System/IO/TextReaderExtensions.cs#L5-L13

**Comment by sneh0195** [comment]
I am manually calling Dispose on IMcpClient since our project uses ".NET Framework 4.7.2"

await mcpClient.DisposeAsync().ConfigureAwait(false);

I am facing the same issue that service hangs and code after this await is not executed all. No exception in thrown.

Is there any workaround for this issue?

**Comment by eiriktsarpalis** [comment]
This has been fixed by https://github.com/modelcontextprotocol/csharp-sdk/pull/588.

**Comment by sneh0195** [comment]
Still facing this issue with SSE transport in .net framework 4.7.2. Works well with streamble http
